<?php

namespace AppBundle\Repository;

/**
 * MeteoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeteoRepository extends \Doctrine\ORM\EntityRepository
{
}
